### ISSUE TITLE
App fails to load in Heroku

### ISSUE THREAD

**Issue by larsen161** [nicksawhney/bernie-sits#34]
I just attempted to simply deploy to Heroku from the Github page and faced the following issue right away.

I created my API key in APIs & Services, restricted the key to Street View Static API leaving application restrictions to None.
I grabbed my Street View Static API secret from: https://console.cloud.google.com/google/maps-apis/credentials

```
Jan 26 11:42:08 my-heroku-app heroku/web.1 Starting process with command `gunicorn --timeout=0 app:app`
Jan 26 11:42:12 my-heroku-app heroku/web.1 State changed from starting to up
Jan 26 11:42:13 my-heroku-app app/web.1 [2021-01-26 19:42:13 +0000] [9] [ERROR] Exception in worker process
Jan 26 11:42:13 my-heroku-app app/web.1 Traceback (most recent call last):
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jan 26 11:42:13 my-heroku-app app/web.1     worker.init_process()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
Jan 26 11:42:13 my-heroku-app app/web.1     self.load_wsgi()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Jan 26 11:42:13 my-heroku-app app/web.1     self.wsgi = self.app.wsgi()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 26 11:42:13 my-heroku-app app/web.1     self.callable = self.load()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
Jan 26 11:42:13 my-heroku-app app/web.1     return self.load_wsgiapp()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Jan 26 11:42:13 my-heroku-app app/web.1     return util.import_app(self.app_uri)
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
Jan 26 11:42:13 my-heroku-app app/web.1     mod = importlib.import_module(module)
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
Jan 26 11:42:13 my-heroku-app app/web.1     return _bootstrap._gcd_import(name[level:], package, level)
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/app.py", line 3, in <module>
Jan 26 11:42:13 my-heroku-app app/web.1     import cv2
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
Jan 26 11:42:13 my-heroku-app app/web.1     from .cv2 import *
Jan 26 11:42:13 my-heroku-app app/web.1 ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Jan 26 11:42:13 my-heroku-app app/web.1 [2021-01-26 19:42:13 +0000] [9] [INFO] Worker exiting (pid: 9)
Jan 26 11:42:13 my-heroku-app app/web.1 [2021-01-26 19:42:13 +0000] [10] [ERROR] Exception in worker process
Jan 26 11:42:13 my-heroku-app app/web.1 Traceback (most recent call last):
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jan 26 11:42:13 my-heroku-app app/web.1     worker.init_process()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
Jan 26 11:42:13 my-heroku-app app/web.1     self.load_wsgi()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Jan 26 11:42:13 my-heroku-app app/web.1     self.wsgi = self.app.wsgi()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 26 11:42:13 my-heroku-app app/web.1     self.callable = self.load()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
Jan 26 11:42:13 my-heroku-app app/web.1     return self.load_wsgiapp()
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Jan 26 11:42:13 my-heroku-app app/web.1     return util.import_app(self.app_uri)
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
Jan 26 11:42:13 my-heroku-app app/web.1     mod = importlib.import_module(module)
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
Jan 26 11:42:13 my-heroku-app app/web.1     return _bootstrap._gcd_import(name[level:], package, level)
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Jan 26 11:42:13 my-heroku-app app/web.1   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/app.py", line 3, in <module>
Jan 26 11:42:13 my-heroku-app app/web.1     import cv2
Jan 26 11:42:13 my-heroku-app app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
Jan 26 11:42:13 my-heroku-app app/web.1     from .cv2 import *
Jan 26 11:42:13 my-heroku-app app/web.1 ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Jan 26 11:42:13 my-heroku-app app/web.1 [2021-01-26 19:42:13 +0000] [10] [INFO] Worker exiting (pid: 10)
Jan 26 11:42:14 my-heroku-app app/web.1 [2021-01-26 19:42:13 +0000] [4] [INFO] Shutting down: Master
Jan 26 11:42:14 my-heroku-app app/web.1 [2021-01-26 19:42:13 +0000] [4] [INFO] Reason: Worker failed to boot.
```

**Comment by nicksawhney** [comment]
Looks like `libgl1` isn't in your `Aptfile`. 

Are you on the most current branch? I cannot replicate this.
